theme = "varda"
client_id = "657a33b23cba437787e4111bd482769e"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists}
{album}
{metadata}"""
notify_timeout_in_secs = 0
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "󰐊"
pause_icon = "󰏤"
liked_icon = ""
border_type = "Rounded"
progress_bar_type = "Rectangle"
cover_img_length = 6
cover_img_width = 3
cover_img_scale = 1.0
enable_media_control = true
enable_streaming = "Always"
enable_notify = false
enable_cover_image_cache = true
default_device = "spotify-player"
notify_streaming_only = false
seek_duration_secs = 5
sort_artist_albums_by_type = true

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[layout]
playback_window_position = "Top"
playback_window_height = 5

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
autoplay = false