include fontSize.conf

shell_integration no-cursor

allow_remote_control yes

update_check_interval 0

font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto

font_family      JetBrainsMono NFM Medium
bold_font        JetBrainsMono NFM ExtraBold
italic_font      JetBrainsMono NFM Medium Italic
bold_italic_font JetBrainsMono NFM ExtraBold Italic

tab_bar_style powerline
tab_powerline_style angled

tab_title_template "{index}  {tab.active_wd}"

active_tab_foreground   #0C0E11
active_tab_background   #D0EBEE
active_tab_font_style   bold
inactive_tab_foreground #0C0E11
inactive_tab_background #52677C
inactive_tab_font_style normal

cursor_shape underline
cursor_underline_thickness 1.0

touch_scroll_multiplier 10.0

foreground #D0EBEE
background #0C0E11

selection_foreground #0C0E11
selection_background #D0EBEE

active_border_color #D0EBEE
inactive_border_color #52677C

mark1_foreground #0C0E11
mark1_background #D0EBEE
mark2_foreground #0C0E11
mark2_background #52677C
mark3_foreground #D0EBEE
mark3_background #52677C

# black
color0 #0C0E11
color8 #141619
# red
color1 #733447
color9 #733447
# green
color2  #257B76
color10 #257B76
# yellow
color3  #C78C56
color11 #C78C56
# blue
color4  #52677C
color12 #52677C
# magenta
color5  #604575
color13 #604575
# cyan
color6  #40AFBF
color14 #40AFBF
# white
color7  #D0EBEE
color15 #D0EBEE