include /home/john/.config/kitty/localTheme/kitty.conf

shell_integration no-cursor

allow_remote_control yes

update_check_interval 0

font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto

font_family      JetBrainsMono NFM Medium
bold_font        JetBrainsMono NFM ExtraBold
italic_font      JetBrainsMono NFM Medium Italic
bold_italic_font JetBrainsMono NFM ExtraBold Italic

tab_bar_style powerline
tab_powerline_style angled

tab_title_template "{index}  {tab.active_wd}"
# active_tab_foreground   #0C0E11
# active_tab_background   #D0EBEE
active_tab_font_style   bold
# inactive_tab_foreground #0C0E11
# inactive_tab_background #52677C
inactive_tab_font_style normal

cursor_shape underline
cursor_underline_thickness 1.0

touch_scroll_multiplier 10.0

confirm_os_window_close 0
