include fontSize.conf

shell_integration no-cursor

font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto

font_family      JetBrainsMono NFM Medium
bold_font        JetBrainsMono NFM ExtraBold
italic_font      JetBrainsMono NFM Medium Italic
bold_italic_font JetBrainsMono NFM ExtraBold Italic

cursor_shape underline
cursor_underline_thickness 1.0

foreground #D0EBEE
background #0C0E11

selection_foreground #000000
selection_background #fffacd

# black
color0 #0C0E11
color8 #141619
# red
color1 #733447
color9 #733447
# green
color2  #257B76
color10 #257B76
# yellow
color3  #C78C56
color11 #C78C56
# blue
color4  #52677C
color12 #52677C
# magenta
color5  #604575
color13 #604575
# cyan
color6  #40AFBF
color14 #40AFBF
# white
color7  #D0EBEE
color15 #D0EBEE