general {
    col.active_border = rgba(E0DEF4FF)
    col.inactive_border = rgba(C4A7E7FF)
}

group {
    col.border_active = rgba(E0DEF4FF)
    col.border_inactive = rgba(C4A7E7FF)
    col.border_locked_active = rgba(E0DEF4FF)
    col.border_locked_inactive = rgba(C4A7E7FF)

    groupbar {
        col.active = rgba(C4A7E7FF)
        col.inactive = rgba(191724FF)
        col.locked_active = rgba(C4A7E7FF)
        col.locked_inactive = rgba(191724FF)
        text_color = rgba(E0DEF4FF)
    }
}

decoration {
    col.shadow = rgba(E0DEF499)
    col.shadow_inactive = rgba(C4A7E700)
}