splash = false

preload = ~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/blankbg.png
preload = ~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/man-planet-river.jpg
preload = ~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/man-planet-river2.jpg
preload = ~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/man-planet-river3.jpg
preload = ~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/dark-woods.jpg
preload = ~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/moon-mountains.jpg
preload = ~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/three-peaks.jpg

# main monitor
wallpaper = desc:LG Electronics LG ULTRAGEAR+ 303NTRL72662,contain:~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/man-planet-river3.jpg
# laptop
wallpaper = desc:BOE 0x0BCA,contain:~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/man-planet-river3.jpg
# other monitors
wallpaper = DP-2,~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/blankbg.png
wallpaper = DP-3,~/workspace/Varda-Theme/setup/themes/varda/hypr/wallpaper/blankbg.png