splash = false

preload = ~/.config/hypr/assets/wallpaper/blankbg.png
preload = ~/.config/hypr/assets/wallpaper/narsil.png
preload = ~/.config/hypr/assets/wallpaper/narsil_laptop.png

wallpaper = DP-1,contain:~/.config/hypr/assets/wallpaper/narsil.png
wallpaper = DP-3,contain:~/.config/hypr/assets/wallpaper/blankbg.png
wallpaper = eDP-1,contain:~/.config/hypr/assets/wallpaper/narsil_laptop.png
