splash = false

preload = ~/.config/hypr/assets/wallpaper/blankbg.png
preload = ~/.config/hypr/assets/wallpaper/narsil.png
preload = ~/.config/hypr/assets/wallpaper/narsil_laptop.png

# main monitor
wallpaper = DP-1,contain:~/.config/hypr/assets/wallpaper/narsil.png
# laptop
wallpaper = desc:BOE 0x0BCA,contain:~/.config/hypr/assets/wallpaper/narsil_laptop.png
# other monitors
wallpaper = DP-2,~/.config/hypr/assets/wallpaper/blankbg.png
wallpaper = DP-3,~/.config/hypr/assets/wallpaper/blankbg.png