foreground #D3C6AA
background #272E33

selection_foreground #272E33
selection_background #D3C6AA

active_border_color #D3C6AA
inactive_border_color #7FBBB3

mark1_foreground #272E33
mark1_background #D3C6AA
mark2_foreground #272E33
mark2_background #7FBBB3
mark3_foreground #D3C6AA
mark3_background #7FBBB3

# black
color0 #272E33
color8 #2E383C
# red
color1 #E67E80
color9 #E67E80
# green
color2  #A7C080
color10 #A7C080
# yellow
color3  #DBBC7F
color11 #DBBC7F
# blue
color4  #7FBBB3
color12 #7FBBB3
# magenta
color5  #D69986
color13 #D69986
# cyan
color6  #83C092
color14 #83C092
# white
color7  #D3C6AA
color15 #D3C6AA
