# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-1,5120x1440@240,0x0,1 #TODO name monitor
#monitor=DP-3,1920x1080@30,5120x0,1 #TODO name monitor

monitor=desc:BOE 0x0BCA,2256x1504@60,0x0,1 # laptop screen
monitor=desc:Dell Inc. DELL U3421WE 6JZ7753,3440x1440@75,-3440x0,1 # devi house office screen