splash = false

preload = ~/workspace/Varda-Theme/setup/themes/everforest/hypr/wallpaper/blankbg.png
preload = ~/workspace/Varda-Theme/setup/themes/everforest/hypr/wallpaper/foggy-autumn-forest.png

# main monitor
wallpaper = desc:LG Electronics LG ULTRAGEAR+ 303NTRL72662,contain:~/workspace/Varda-Theme/setup/themes/everforest/hypr/wallpaper/foggy-autumn-forest.png
# laptop
wallpaper = desc:BOE 0x0BCA,contain:~/workspace/Varda-Theme/setup/themes/everforest/hypr/wallpaper/foggy-autumn-forest.png
# other monitors
wallpaper = DP-2,~/workspace/Varda-Theme/setup/themes/everforest/hypr/wallpaper/blankbg.png
wallpaper = DP-3,~/workspace/Varda-Theme/setup/themes/everforest/hypr/wallpaper/blankbg.png