# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/john/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"
ZSH_THEME="varda"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git cp)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias sweep="/home/john/Documents/scripts/sweepGitBranches.sh"
alias install="sudo pacman -Syu"
alias update="sudo pacman -Syu"
alias remove="sudo pacman -Rcns"
alias uninstall="sudo pacman -Rcns"
alias adb="/home/john/Android/Sdk/platform-tools/adb"
alias fastboot="/home/john/Android/Sdk/platform-tools/fastboot"
alias bashtop=bpytop
alias sshpi="ssh john@192.168.50.158"
alias ewww="eww --config $HOME/.config/hypr/components/eww"
alias agss="ags --config $HOME/.config/hypr/components/ags/sidebarConfig.js"
alias agst="ags --config $HOME/.config/hypr/components/ags/topbarConfig.js"

# Change folder colors
# ========= Font ================
# 0 default color
# 1 bold
# 4 underline
# 5 flashing text
# 8 invisible
# ======== Colors ================
# 31 red
# 32 green
# 33 orange
# 34 blue
# 35 purple
# 36 cyan
# 37 grey
# 90 dark grey
# 91 light red
# 92 light green
# 93 yellow
# 94 light blue
# light purple
# 96 turqoise
# 97 white
# ========= Background Colors ===========
# 40 black
# 41 red
# 42 green
# 43 orange
# 44 blue
# 45 purple
# 46 cyan
# 47 grey
# 100 dark grey
# 101 light red
# 102 light green
# 103 yellow
# 104 light blue
# 105 light purple
# 106 turqoise
# 107 white
# ============== Definitions ==================
# [bd]="block device"
# [ca]="file with capability"
# [cd]="character device"
# [di]="directory"
# [do]="door"
# [ex]="executable file"
# [fi]="regular file"
# [ln]="symbolic link"
# [mh]="multi-hardlink"
# [mi]="missing file"
# [no]="normal non-filename text"
# [or]="orphan symlink"
# [ow]="other-writable directory"
# [pi]="named pipe, AKA FIFO"
# [rs]="reset to no color"
# [sg]="set-group-ID"
# [so]="socket"
# [st]="sticky directory"
# [su]="set-user-ID"
# [tw]="sticky and other-writable directory"
LS_COLORS=$LS_COLORS:'di=1;37:'
LS_COLORS=$LS_COLORS:'ln=4;37:'
LS_COLORS=$LS_COLORS:'ow=1;37;41:'
LS_COLORS=$LS_COLORS:'*.bak=00;31:'
export LS_COLORS

# start yazi.  Makes it so when you quit yazi, you are in the same directory that you were in last
function ya() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

fastfetch
